export const DISPUTE_STATUS = {
  PENDING: "pending",
  APPROVED: "approved",
  REJECTED: "rejected",
  PARTIALLY_APPROVED: "partially_approved",
};

export const ACTION_TYPES = {
  CREATED: "CREATED",
  LEAD_APPROVED: "LEAD_APPROVED",
  LEAD_REJECTED: "LEAD_REJECTED",
  ADMIN_APPROVED: "ADMIN_APPROVED",
  ADMIN_REJECTED: "ADMIN_REJECTED",
  HR_APPROVED: "HR_APPROVED",
  HR_REJECTED: "HR_REJECTED",
  OVERRIDDEN: "OVERRIDDEN",
  REOPENED: "REOPENED",
  ESCALATED: "ESCALATED",
};
